export const Countrys = [
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Antígua e Barbuda",
  "Arábia Saudita",
  "Argentina",
  "Armênia",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Bélgica",
  "Belize",
  "Benin",
  "Bermudas",
  "Butão",
  "Bolívia",
  "Bósnia e Herzegovina",
  "Botsuana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Camboja",
  "Camarões",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Colômbia",
  "Comores",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "Djibuti",
  "Dominica",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritreia",
  "Eslováquia",
  "Eslovênia",
  "Espanha",
  "Estados Unidos",
  "Estônia",
  "Eswatini",
  "Etiópia",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gâmbia",
  "Gana",
  "Geórgia",
  "Granada",
  "Grécia",
  "Guatemala",
  "Guiana",
  "Guiné",
  "Guiné-Bissau",
  "Guiné Equatorial",
  "Haiti",
  "Holanda",
  "Honduras",
  "Hungria",
  "Iêmen",
  "Ilhas Cook",
  "Ilhas Marshall",
  "Índia",
  "Indonésia",
  "Irã",
  "Iraque",
  "Irlanda",
  "Islândia",
  "Israel",
  "Itália",
  "Jamaica",
  "Japão",
  "Jordânia",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letônia",
  "Líbano",
  "Libéria",
  "Líbia",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Madagáscar",
  "Malásia",
  "Malawi",
  "Maldivas",
  "Mali",
  "Malta",
  "Marrocos",
  "Maurícia",
  "Mauritânia",
  "México",
  "Micronésia",
  "Moçambique",
  "Moldávia",
  "Mônaco",
  "Mongólia",
  "Montenegro",
  "Myanma",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Nicarágua",
  "Níger",
  "Nigéria",
  "Noruega",
  "Nova Zelândia",
  "Omã",
  "Países Baixos",
  "Palau",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "Peru",
  "Polônia",
  "Portugal",
  "Quênia",
  "Quirguistão",
  "Reino Unido",
  "República Centro-Africana",
  "República Democrática do Congo",
  "República Dominicana",
  "República do Congo",
  "República Tcheca",
  "Romênia",
  "Ruanda",
  "Rússia",
  "Samoa",
  "San Marino",
  "Santa Lúcia",
  "São Cristóvão e Neves",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Senegal",
  "Serra Leoa",
  "Sérvia",
  "Singapura",
  "Síria",
  "Somália",
  "Sri Lanka",
  "Suazilândia",
  "Sudão",
  "Sudão do Sul",
  "Suécia",
  "Suíça",
  "Suriname",
  "Tailândia",
  "Taiwan",
  "Tajiquistão",
  "Tanzânia",
  "Togo",
  "Tonga",
  "Trinidad e Tobago",
  "Tunísia",
  "Turcomenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietnã",
  "Zâmbia",
  "Zimbábue",
];
